databases:
  - name: helpjuice
    databaseName: DEV_DB_NAME
    user: DEV_DB_USERNAME
    plan: free

services:
  - type: web
    name: helpjuice
    plan: free
    buildCommand: bundle exec rake assets:precompile
    startCommand: bundle exec rails server -p $PORT
    runtime: ruby
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjuice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false