databases:
  - name: helpjuice
    databaseName: helpjuice
    user: helpjuice
    plan: free

services:
  - type: web
    name: helpjuice
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    runtime: ruby  # Specify the runtime environment
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjuice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false