default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  
  database: <%= ENV['DEV_DB_NAME'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  host: <%= ENV['DEV_DB_HOSTNAME'] %>
test:
  <<: *default
  database: <%= ENV['DEV_DB_NAME_TEST'] %>

production:
  <<: *default
  database: db/production.sqlite3
